package cpdt.common.enums;

/**
 * Defines the severity level assigned to an alert generated by the Digital Twin.
 *
 * <p>Severity levels indicate the urgency of operator attention and are
 * used for alarm prioritization and notification.
 *
 * @since 1.0
 */
public enum AlertSeverity {
    INFO,
    WARNING_LOW,
    WARNING_HIGH,
    CRITICAL_HIGH,
    CRITICAL_LOW
}