package cpdt.common.dto;

import cpdt.common.enums.AlertSeverity;

/**
 * Represents an alert generated by the backend and published to interested
 * subscribers. Each instance contains the alert identifier, affected device,
 * severity, descriptive message, and creation timestamp.
 *
 * @param alertId unique identifier of the alert
 * @param deviceId identifier of the device associated with the alert
 * @param severity severity level of the alert
 * @param message human-readable description of the alert
 * @param timestamp time at which the alert was generated, in milliseconds since the Unix epoch
 */
public record AlertMessage(
        String alertId,
        String deviceId,
        AlertSeverity severity,
        String message,
        long timestamp
) {}