package cpdt.backend.mqtt;

import cpdt.common.dto.DeviceStatusMessage;
import cpdt.common.utils.TelemetrySerializer;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import org.eclipse.paho.client.mqttv3.*;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Component;

/**
 * Publishes device status updates to the MQTT broker.
 *
 * <p>This component establishes an MQTT connection and publishes device
 * status messages generated by the backend. Published messages notify
 * external systems, including the simulator, whenever a device's
 * operational status changes.
 *
 * <p>The publisher manages the MQTT client lifecycle, including
 * connection establishment and graceful shutdown.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
@Component
public class DeviceStatusPublisher {

    private final MqttClient mqttClient;
    private final MqttConnectOptions connectOptions;

    private final int qos;

    /**
     * Creates a publisher for device status messages.
     *
     * @param brokerUrl the MQTT broker URL
     * @param clientId the MQTT client identifier
     * @param qos the Quality of Service level for published messages
     * @throws MqttException if the MQTT client cannot be created
     */
    public DeviceStatusPublisher(@Value("${mqtt.broker}") String brokerUrl, @Value("${mqtt.client-id}") String clientId,
                                 @Value("${mqtt.qos}") int qos) throws MqttException {
        this.qos = qos;
        this.mqttClient = new MqttClient(brokerUrl, clientId + "-status-publisher", new MemoryPersistence());
        this.connectOptions = new MqttConnectOptions();
        this.connectOptions.setAutomaticReconnect(true);
        this.connectOptions.setCleanSession(true);
        this.connectOptions.setConnectionTimeout(10);
        this.connectOptions.setKeepAliveInterval(30);
    }
    /**
     * Establishes a connection to the MQTT broker.
     *
     * <p>This method is automatically invoked during component initialization
     * to ensure the publisher is ready before messages are transmitted.
     *
     * @throws MqttException if the broker connection cannot be established
     */
    @PostConstruct
    public void connect() throws MqttException {
        if (!mqttClient.isConnected()) {
            mqttClient.connect(connectOptions);
        }
    }
    /**
     * Publishes a device status update to the MQTT broker.
     *
     * <p>The supplied status message is serialized into JSON and published
     * to the device-specific MQTT topic using the configured Quality of
     * Service (QoS) level.
     *
     * @param message the device status message to publish
     */
    public synchronized void publish(DeviceStatusMessage message) {
        try {
            String topic = "cpdt/device-status/" + message.deviceId();
            byte[] payload = TelemetrySerializer.toJson(message);
            MqttMessage mqttMessage = new MqttMessage(payload);
            mqttMessage.setQos(qos);
            mqttClient.publish(topic, mqttMessage);

        }
        catch (Exception e) {
            System.err.println("Failed to publish device status: " + e.getMessage());
        }
    }
    /**
     * Closes the MQTT connection and releases associated resources.
     *
     * <p>This method is automatically invoked during application shutdown
     * to disconnect the MQTT client gracefully.
     */
    @PreDestroy
    public void shutdown() {
        try {
            if (mqttClient.isConnected()) {
                mqttClient.disconnect();
            }
            mqttClient.close();
        }
        catch (Exception ignored) { }
    }
}