package cpdt.backend.exception;

import java.time.Instant;

/**
 * Immutable standardized error response returned by the backend.
 *
 * <p>This record encapsulates the HTTP status code, error description,
 * detailed error message, and timestamp associated with an exception.
 * It provides a consistent response format for all REST API error
 * responses generated by the application.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
public record ErrorResponse(
        int status,
        String error,
        String message,
        Instant timestamp)
{ }