package cpdt.backend.repositories;

import cpdt.backend.entities.AlertEntity;

import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * Repository for accessing persisted alert records.
 *
 * <p>Provides database operations for storing, retrieving, and querying
 * alerts generated by the Digital Twin backend.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
public interface AlertRepository extends JpaRepository<AlertEntity, String> {
    List<AlertEntity> findByAcknowledgedFalse();
}