spring.application.name=backend

spring.profiles.active=local

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

mqtt.broker=${BROKER_URL}
mqtt.client-id=cpdt-backend
mqtt.topic=cpdt/#
mqtt.qos=1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

logging.level.root=OFF

spring.jpa.show-sql=false

logging.level.org.hibernate=OFF
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework=OFF