package cpdt.backend.entities;

import cpdt.common.enums.AlertSeverity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;

/**
 * Represents an alarm generated by the Digital Twin backend.
 *
 * <p>This entity stores alerts produced during telemetry evaluation,
 * including the affected device, alarm severity, descriptive message,
 * occurrence time, and acknowledgement status. Each alert is uniquely
 * identified and persisted for historical analysis and operator review.
 *
 * <p>Alert records provide a permanent history of abnormal process
 * conditions detected within the plant.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
@Entity
@Table(
    name = "alerts",
    indexes = {@Index(name = "idx_alerts_device_timestamp", columnList = "deviceId,timestamp")}
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AlertEntity {

    @Id
    @Column(nullable = false, updatable = false)
    private String alertId;

    @Column(nullable = false)
    private String deviceId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertSeverity severity;

    @Column(nullable = false, length = 500)
    private String message;

    @Column(nullable = false)
    private Instant timestamp;

    @Column(nullable = false)
    @Builder.Default
    private boolean acknowledged = false;
}