package cpdt.simulator.mqtt;

import cpdt.common.dto.TelemetryPacket;
import cpdt.common.utils.TelemetrySerializer;
import cpdt.common.utils.TopicBuilder;
import cpdt.simulator.engine.TelemetryPublisher;

import org.eclipse.paho.client.mqttv3.*;
import org.eclipse.paho.client.mqttv3.persist.MemoryPersistence;

import java.util.ArrayDeque;
import java.util.Queue;

/**
 * MQTT implementation of the {@link TelemetryPublisher} interface responsible
 * for publishing telemetry packets generated by the simulator.
 *
 * <p>
 * This publisher serializes telemetry data into JSON, constructs the
 * appropriate MQTT topic, and transmits messages using the Eclipse Paho
 * MQTT client. A bounded retry buffer is maintained so that telemetry
 * generated during temporary connection failures can be retransmitted
 * once communication with the broker is restored.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
public class MqttTelemetryPublisher implements TelemetryPublisher {

    private static final int QOS = 1;
    private static final int MAX_BUFFER_SIZE = 10_000;

    private final MqttClient mqttClient;
    private final MqttConnectOptions connectOptions;

    private final Queue<TelemetryPacket> retryBuffer;

    /**
     * Creates a new MQTT telemetry publisher and establishes a connection
     * to the specified MQTT broker.
     *
     * @param brokerUrl the MQTT broker URL
     * @param clientId the unique MQTT client identifier
     * @throws MqttException if the MQTT client cannot be initialized or connected
     */
    public MqttTelemetryPublisher(String brokerUrl, String clientId) throws MqttException {
        this.retryBuffer = new ArrayDeque<>();
        this.mqttClient = new MqttClient(brokerUrl, clientId, new MemoryPersistence());
        this.connectOptions = new MqttConnectOptions();
        this.connectOptions.setAutomaticReconnect(true);
        this.connectOptions.setCleanSession(true);
        this.connectOptions.setConnectionTimeout(10);
        this.connectOptions.setKeepAliveInterval(30);
        mqttClient.setCallback(new MqttCallback() {
            @Override
            public void connectionLost(Throwable cause) {
                System.err.println("MQTT connection lost: " + (cause != null ? cause.getMessage() : "unknown"));
            }
            @Override
            public void messageArrived(String topic, MqttMessage message) { }
            @Override
            public void deliveryComplete(IMqttDeliveryToken token) { }
        });
        connect();
    }

    /**
     * Establishes a connection to the MQTT broker if one does not already exist.
     *
     * @throws MqttException if the connection attempt fails
     */
    private synchronized void connect() throws MqttException {
        if (mqttClient.isConnected()) {
            return;
        }
        mqttClient.connect(connectOptions);
        System.out.println("Connected to MQTT broker: " + mqttClient.getServerURI());
    }
    /**
     * Publishes a telemetry packet to the MQTT broker.
     * <p>
     * If publishing fails, the packet is stored in the retry buffer for
     * retransmission when connectivity is restored.
     *
     * @param packet the telemetry packet to publish
     */
    @Override
    public synchronized void publish(TelemetryPacket packet) {
        if (packet == null) {
            return;
        }
        try {
            ensureConnected();
            flushRetryBuffer();
            publishInternal(packet);
        }
        catch (Exception e) {
            queueForRetry(packet);
            System.err.println("Failed to publish telemetry. Added to retry queue.");
        }
    }
    /**
     * Serializes and publishes a telemetry packet to its corresponding MQTT topic.
     *
     * @param packet the telemetry packet to publish
     * @throws MqttException if the MQTT publish operation fails
     */
    private void publishInternal(TelemetryPacket packet) throws MqttException {
        String topic = TopicBuilder.build(packet);
        byte[] payload = TelemetrySerializer.toJson(packet);
        MqttMessage mqttMessage = new MqttMessage(payload);
        mqttMessage.setQos(QOS);
        mqttClient.publish(topic, mqttMessage);
    }
    /**
     * Attempts to publish all queued telemetry packets stored in the retry buffer.
     * Successfully transmitted packets are removed from the queue.
     */
    private void flushRetryBuffer() {
        if (!mqttClient.isConnected()) {
            return;
        }
        while (!retryBuffer.isEmpty()) {
            TelemetryPacket packet = retryBuffer.peek();
            try {
                publishInternal(packet);
                retryBuffer.poll();
            }
            catch (Exception e) {
                break;
            }
        }
    }
    /**
     * Adds a telemetry packet to the retry buffer.
     * If the buffer has reached its maximum capacity, the oldest packet is discarded.
     *
     * @param packet the telemetry packet to be queued
     */
    private void queueForRetry(TelemetryPacket packet) {
        if (retryBuffer.size() >= MAX_BUFFER_SIZE) {
            retryBuffer.poll();
        }
        retryBuffer.offer(packet);
    }
    /**
     * Ensures that an active connection to the MQTT broker exists before
     * attempting any publish operations.
     *
     * @throws MqttException if reconnection to the broker fails
     */
    private void ensureConnected() throws MqttException {
        if (!mqttClient.isConnected()) {
            connect();
        }
    }
    /**
     * Gracefully disconnects from the MQTT broker and releases all MQTT resources.
     */
    public synchronized void shutdown() {
        try {
            if (mqttClient.isConnected()) {
                mqttClient.disconnect();
            }
            mqttClient.close();
            System.out.println("MQTT publisher shutdown completed.");
        }
        catch (Exception e) {
            System.err.println("Error during MQTT shutdown: " + e.getMessage());
        }
    }
}