package cpdt.simulator.engine;

import cpdt.common.dto.TelemetryPacket;

/**
 * Defines the contract for publishing telemetry packets generated by the
 * simulator.
 * <p>
 * Implementations determine how telemetry is transmitted to downstream
 * consumers, allowing the simulator to remain independent of any specific
 * communication technology or messaging protocol.
 *
 * @author Lakshmi Sanjeev
 * @since 1.0
 */
public interface TelemetryPublisher {
    /**
     * Publishes a telemetry packet to the configured destination.
     *
     * @param telemetryPacket the telemetry packet to publish
     */
    void publish(TelemetryPacket telemetryPacket);
}